// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEnVExM5GcOMBH3L4Txp8kmIDsVnIQmwM',
    appId: '1:473932150734:web:e14103f6da6411ac201d9f',
    messagingSenderId: '473932150734',
    projectId: 'cosmetics-mobileapp',
    authDomain: 'cosmetics-mobileapp.firebaseapp.com',
    storageBucket: 'cosmetics-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-Isf-LUlW6JkjZIS547HuxPzX4jCPGo',
    appId: '1:473932150734:android:9399fc4bd278d38d201d9f',
    messagingSenderId: '473932150734',
    projectId: 'cosmetics-mobileapp',
    storageBucket: 'cosmetics-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTX78cmsbJUiEMLoq7f8Dwlv5ttmqYOfY',
    appId: '1:473932150734:ios:50f9e01aa1bca536201d9f',
    messagingSenderId: '473932150734',
    projectId: 'cosmetics-mobileapp',
    storageBucket: 'cosmetics-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.cosmeticsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTX78cmsbJUiEMLoq7f8Dwlv5ttmqYOfY',
    appId: '1:473932150734:ios:50f9e01aa1bca536201d9f',
    messagingSenderId: '473932150734',
    projectId: 'cosmetics-mobileapp',
    storageBucket: 'cosmetics-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.cosmeticsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEnVExM5GcOMBH3L4Txp8kmIDsVnIQmwM',
    appId: '1:473932150734:web:8a99f8e60bfed44f201d9f',
    messagingSenderId: '473932150734',
    projectId: 'cosmetics-mobileapp',
    authDomain: 'cosmetics-mobileapp.firebaseapp.com',
    storageBucket: 'cosmetics-mobileapp.firebasestorage.app',
  );
}
