// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOP_Hg8ZRR_CE36Znp46JYkg4JSy_QAY',
    appId: '1:245127718770:web:dbd3bcbd0da7433c1adfeb',
    messagingSenderId: '245127718770',
    projectId: 'cosmetics-mobileapp-2c4e4',
    authDomain: 'cosmetics-mobileapp-2c4e4.firebaseapp.com',
    storageBucket: 'cosmetics-mobileapp-2c4e4.firebasestorage.app',
    measurementId: 'G-VJP6VZHTYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCytSkzztFMXZ_YGlculF0rJyeoTBQ9WaE',
    appId: '1:245127718770:android:c89a644f6b3af44f1adfeb',
    messagingSenderId: '245127718770',
    projectId: 'cosmetics-mobileapp-2c4e4',
    storageBucket: 'cosmetics-mobileapp-2c4e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtiujaDf--aP7kQ03q1TFe2CTcs6m9XPc',
    appId: '1:245127718770:ios:38d46caca7a0ff331adfeb',
    messagingSenderId: '245127718770',
    projectId: 'cosmetics-mobileapp-2c4e4',
    storageBucket: 'cosmetics-mobileapp-2c4e4.firebasestorage.app',
    iosBundleId: 'com.example.cosmeticsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtiujaDf--aP7kQ03q1TFe2CTcs6m9XPc',
    appId: '1:245127718770:ios:38d46caca7a0ff331adfeb',
    messagingSenderId: '245127718770',
    projectId: 'cosmetics-mobileapp-2c4e4',
    storageBucket: 'cosmetics-mobileapp-2c4e4.firebasestorage.app',
    iosBundleId: 'com.example.cosmeticsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmOP_Hg8ZRR_CE36Znp46JYkg4JSy_QAY',
    appId: '1:245127718770:web:a5ff0dcd854b84181adfeb',
    messagingSenderId: '245127718770',
    projectId: 'cosmetics-mobileapp-2c4e4',
    authDomain: 'cosmetics-mobileapp-2c4e4.firebaseapp.com',
    storageBucket: 'cosmetics-mobileapp-2c4e4.firebasestorage.app',
    measurementId: 'G-NX2ZW97PXH',
  );

}